### ISSUE TITLE
Sort by ratio doesn't work properly

### ISSUE THREAD

**Issue by retro-78** [vuze/vuze-remote-for-android#1]
Hello,
First of all, thank you for this great app !
I have noticed that sorting torrents by ratio doesn't take into account the digits after the comma. Is it normal or an issue ?
Thank you

**Comment by ArronM** [comment]
Thanks for the report.  We noticed this bug too, and it will be fixed in the next release (2.6.2).  You can either wait until the official release, or join the beta on Google Play for our app, which is has 2.6.2 beta2.

**Comment by retro-78** [comment]
Ok thank you, I use the F-Droid repo so I will wait for the next release.
